name: Build Web
run-name: Build Web
on:
  workflow_dispatch: {}

jobs:
  Build_Web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: |
          flutter pub get
          
      - run: |
          flutter build web --release

      - uses: actions/upload-artifact@v4
        with:
          name: web_build
          path: build/web/
